# Generated by Django 3.1.6 on 2021-02-20 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210216_1557'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='category',
            field=models.ForeignKey(
                blank=True, max_length=254, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.category'),
        ),
        migrations.AddField(
            model_name='stock',
            name='sub_category',
            field=models.ForeignKey(
                blank=True, max_length=254, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='products.sub_category'),
        ),
    ]
