# Generated by Django 3.1.6 on 2021-02-20 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_auto_20210220_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='category',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='sub_category',
        ),
    ]
