# Generated by Django 3.1.6 on 2021-02-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_auto_20210220_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='issue_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='receive_qty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
