# Generated by Django 3.1.6 on 2021-02-28 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210216_1557'),
        ('stock', '0005_stocktransactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='product',
            field=models.ForeignKey(
                max_length=254,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='transaction', to='products.product'),
        ),
    ]
