# Generated by Django 3.1.6 on 2021-03-01 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_in_stock'),
        ('stock', '0006_auto_20210228_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='product',
            field=models.ForeignKey(max_length=254, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
