# Generated by Django 3.1.6 on 2021-03-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_in_stock'),
        ('stock', '0007_auto_20210301_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransactions',
            name='product',
            field=models.ForeignKey(max_length=254, on_delete=django.db.models.deletion.CASCADE, related_name='stockproduct', to='products.product'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
