# Generated by Django 3.1.6 on 2021-03-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_admin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chart',
        ),
    ]
