# Generated by Django 3.1.6 on 2021-02-21 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20210221_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='default_town_or_city',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
