# Generated by Django 3.1.6 on 2021-02-10 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_friendlyname',
            new_name='subcat_friendlyname',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='sub_name',
            new_name='subcat_name',
        ),
    ]
