# Generated by Django 3.1.6 on 2021-02-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210210_1105'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sub_category',
            options={'verbose_name_plural': 'Sub Categories'},
        ),
    ]
